### ISSUE TITLE
add hover animations on navbar

### ISSUE THREAD

**Issue by IshaanTyagi** [Newton-School-Coding-Club-ABESEC/team#6]
Add some hover animation for the navbar with some decent transitions.

**Comment by piyush-sri** [comment]
I would like to work on this issue please assign it to me

**Comment by Ankur-Sh** [comment]
pls assign it to me @IshaanTyagi

**Comment by IshaanTyagi** [comment]
I am assigning this issue to you @Ankur-Sh
